### ISSUE TITLE
容器配置时区为东八时区

### ISSUE THREAD

**Issue by DesireWithin** [rea1shane/a2w#4]
现在输出的时间是 UTC时间, 我们应该设置成+8时区
我正在尝试参考:
https://cloud.tencent.com/developer/article/1666529
编辑`dockerfile` 以及`a2w.go`
有进展同步.

**Comment by DesireWithin** [comment]
经测试, 将基镜像(基于debian)的 `/usr/share/zoneinfo` 拷贝后, 并制定`TZ` 后, 时区生效
```dockerfile
FROM golang:1.20 as builder

ENV GO111MODULE=on \
    GOPROXY=https://goproxy.cn,direct

WORKDIR /usr/src/app

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY a2w.go .
RUN CGO_ENABLED=0 go build -o /usr/local/bin/a2w a2w.go

FROM scratch

ENV GIN_MODE=release

WORKDIR /app

COPY --from=builder /usr/share/zoneinfo /usr/share/zoneinfo  #新增行, 也可使用args定义变量
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /usr/local/bin/a2w .
COPY templates templates

ENV TZ=Asia/Shanghai   #新增行, 也可使用ARG定义变量

EXPOSE 5001

ENTRYPOINT ["./a2w"]

```

**Comment by rea1shane** [comment]
Hi @DesireWithin 

我想了解一下为何要添加时区？目前使用中没有遇到过时间错误的问题。

而且 Prometheus 也是 UTC 时区，并且不能修改，官方文档：[Can I change the timezone? Why is everything in UTC?](https://prometheus.io/docs/introduction/faq/#can-i-change-the-timezone-why-is-everything-in-utc)

**Comment by DesireWithin** [comment]
我们在输出企业微信消息的时候, 初始信息是不带时区的时间, 显示有歧义.
![图片](https://github.com/rea1shane/a2w/assets/23254001/ea14ce7a-b5ad-415c-8cef-657ea8d69f76)
和普罗米修斯的时区无关.
而通知模板的代码在这里, 没有输出时区. https://github.com/rea1shane/a2w/blob/5ec3f484e5c1d8c4e91a11d4b3ccb87023616ecb/a2w.go#L196

**Comment by rea1shane** [comment]
> 我们在输出企业微信消息的时候, 初始信息是不带时区的时间, 显示有歧义.

我测试了一下确实是有这个问题，a2w 容器内的时区不是上海时区，这个项目一般是在中国使用的，所以改为东八时区还是有意义的。

你愿意提交一个 PR 么？感谢你指出这个问题。

**Comment by rea1shane** [comment]
感谢你指出这个问题，我已经合并了相关内容。
